# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, e.g. receiver/prometheus, exporter/otlp, etc.
component: exporter/otlp

# A brief description of the change. Surround your text with quotes ("...") if it needs to start with a backtick (`)
description: Add sending queue size and num consumers to exporter metrics

# One or more tracking issues related to the change
issues: [14412]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the changelog.
# Use pipe (|) for multiline entries.
notes: |
  Exporters now emit metrics for the sending queue size and number of
  consumers when the sending queue is enabled. This allows operators
  to monitor queue utilization and tune queue configuration accordingly.
